### ISSUE TITLE
如何获取预览图像保存到bitmap

### ISSUE THREAD

**Issue by jinyingfeng** [ChillingVan/AndroidInstantVideo#12]
如何从
public void onGLDraw(ICanvasGL canvasGL, List<GLTexture> producedTextures, List<GLTexture> consumedTextures) {

                GLTexture texture = producedTextures.get(0);
                SurfaceTexture surfaceTexture = texture.getSurfaceTexture();
                RawTexture rawTexture = texture.getRawTexture();
                canvasGL.drawSurfaceTexture(rawTexture, surfaceTexture, 0, 0, rawTexture.getWidth(), rawTexture.getHeight());
            }
获取照片？
谢谢

**Comment by inventionsbyhamid** [comment]
There is a method getDrawingBitmap() with that you can get the current bitmap. You have to pass the Rect with coordinates to capture and a GLView.GetDrawingCacheCallback listener to get bitmap.

**Comment by ChillingVan** [comment]
@inventionsbyhamid Thanks.
@jinyingfeng Example: https://github.com/ChillingVan/android-openGL-canvas/blob/master/canvasglsample/src/main/java/com/chillingvan/canvasglsample/textureView/TextureCameraActivity.java

**Comment by jinyingfeng** [comment]
@inventionsbyhamid @ChillingVan thanks !
