### ISSUE TITLE
第二次录制mp4muxer出现黑屏问题。

### ISSUE THREAD

**Issue by yesbutter** [ChillingVan/AndroidInstantVideo#20]
when i started the first recorder，it was no problem。
but when the second，don't close the mp4muxeractivity,the video is all black,only has vioce.
i think it is something error in restart recorder.but i can't in short time to understand the project.

in the same time i want to try pause recorder the video,but the aacEncoder don't find pause,when i try restart it occur bug.

**Comment by ChillingVan** [comment]
Fixed. But mp4 recorder cannot be paused because it must generate a new file. You need to merge the new file and the old file.
