### ISSUE TITLE
Need help: Using surface created in SurfaceTextureCreatedListener to display screen using MediaProjection 

### ISSUE THREAD

**Issue by inventionsbyhamid** [ChillingVan/AndroidInstantVideo#25]
We can display screen using the following sample: https://github.com/android/media-samples/tree/master/ScreenCapture

MediaProjection requires to give a surface to draw screen frames. I am modifying the TestCameraPublisherActivity to also include the screen display on the textureview. When I pass the surface obtained in the SurfaceTextureCreatedListener to media projection, nothing is drawn when i use canvasGL.drawSurfaceTexture, I also set the onFrameAvailable on the SurfaceTexture and can see that it is being called for screen display.

Any help as to why drawing the screen display surface texture does not show on the preview?

**Comment by ChillingVan** [comment]
Could you show your code as an example?

**Comment by ChillingVan** [comment]
And is requestRender called?

**Comment by inventionsbyhamid** [comment]
Here is the link https://github.com/inventionsbyhamid/AndroidInstantVideo/tree/screen_display
I have created a separate activity "ScreenPublisherActivity" to just draw the screen preview. Not able to figure out why nothing gets drawn on the texture view.

**Comment by ChillingVan** [comment]
I check and the onFrameAvailable is not called, I am wondering why

**Comment by ChillingVan** [comment]
It seems that the surface in ImageReader works fine. Need to look into the source code of it.

**Comment by ChillingVan** [comment]
I try to use 
```
                surfaceTexture.setDefaultBufferSize(width, height);
```.
And it works.
Add this line to onFrameAvailable:
![图片](https://user-images.githubusercontent.com/7666419/74216791-7656b280-4ce0-11ea-9374-478ebd1541e7.png)

**Comment by inventionsbyhamid** [comment]
It works fine. Thanks for the help!
