### ISSUE TITLE
视频预览方向不对

### ISSUE THREAD

**Issue by renwfy** [ChillingVan/AndroidInstantVideo#7]
三星，视频预览方向不对

**Comment by ChillingVan** [comment]
例子里并没有刻意改摄像头预览方向。

**Comment by jinyingfeng** [comment]
我也遇到这个问题，后摄像头预览是镜像图像，怎么办？

**Comment by ChillingVan** [comment]
这类问题，第一可以修改Camera本身的预览方向。也可以用本库的API里的canvas，修改绘制时的方向

**Comment by jinyingfeng** [comment]
很感谢您的回复，Camera通过改变角度，90,270,180都没有用的，预览图像是反的

**Comment by jinyingfeng** [comment]
谢谢，已经搞定，rawTexture.setIsFlippedVertically(true);就可以了
